.Dd December 19, 2019
.Dt A-NEW-HOPE 7
.Os
.Sh NAME
.Nm a-new-hope
.Nd cliche first blog post?
.Sh DESCRIPTION
Toying with the thought of starting a website/blog.
.Pp
Exploring my hosting options and pleasantly surprised that
.Lk https://fastmail.com FastMail
has free static site hosting!
.Pp
Inspired by Jeff Huang's article on websites Designed to Last
and a general desire for a simpler web.
.Sh SEE ALSO
.Bl -compact -bullet -format=indent
.It
.Lk https://jeffhuang.com/designed_to_last
.It
.Xr blog 7
.El
