.Dd July 13, 2020
.Dt BLM 7
.Os
.Sh NAME
.Nm BLM
.Nd Black Lives Matter
.Sh DESCRIPTION
I meant to post about this earlier, but it's better late than never.
.Pp
It's become abundantly clear to me that we need serious structural changes in our country.
I want to raise my voice in solidarity to say that Black Lives Matter.
.Sh SEE ALSO
.Bl -compact -bullet
.It
.Lk https://blacklivesmatter.com
.It
.Xr blog 7
.El
