.Dd $Mdocdate$
.Dt BLOG 7
.Os
.Sh NAME
.Nm blog
.Nd yet another weblog
.Sh DESCRIPTION
I don't write frequently, but when I do, it's usually about tech.
.Pp
If you'd like to get notifications on new articles, I publish an
.Lk atom.xml Atom
feed (for use with your favorite RSS/Atom client).
.Pp
For an up to date list of software/hardware I use, see
.Xr uses 7 .
.Sh POSTS
.Bl -tag -width "XX/XX"
.It 11/21
.Xr use-git 7
- non-standard uses of
.Xr git 1
.It 09/21
.Xr make-obj 7
- out-of-tree builds with BSD
.Xr make 1
.It 09/21
.Xr text-only 7
- announcing text.alexkarle.com
.It 07/21
.Xr creative-coding 7
- learning through creative limitation
.It 02/21
.Xr use-feeds 7
- RSS/Atom feeds; what, why, and how
.It 12/20
.Xr my-old-man 7
- Adventures in using
.Xr mdoc 7
for this site
.It 10/20
.Xr on-writing 7
- On Writing Without an Audience
.It 07/20
.Xr self-hosted 7
- Migrating to a Self-Hosted Site
.It 07/20
.Xr BLM 7
- Black Lives Matter
.It 03/20
.Xr domain-names 7
- What's in a (domain) name?
.It 12/19
.Xr a-new-hope 7
- A New Hope
.El
.Sh SEE ALSO
.Bl -bullet -compact
.It
.Xr intro 7
.It
.Xr jam-tuesday 7
.El
