.Dd $Mdocdate$
.Dt BLOG 7
.Os
.Sh NAME
.Nm blog
.Nd yet another weblog
.Sh DESCRIPTION
I don't write frequently, but when I do, it's usually about tech.
.Pp
If you'd like to get notifications on new articles, I publish an
.Lk atom.xml Atom
feed (for use with your favorite RSS/Atom client).
.Pp
From newest to oldest:
.Bl -bullet -compact
.It
.Xr my-old-man 7
- Adventures in using
.Xr mdoc 7
for this site's source (12/30/2020)
.It
.Xr on-writing 7
- On Writing Without an Audience (10/22/2020)
.It
.Xr self-hosted 7
- Migrating to a Self-Hosted Site (07/19/2020)
.It
.Xr BLM 7
- Black Lives Matter (07/13/2020)
.It
.Xr domain-names 7
- What's in a (domain) name? (03/24/2020)
.It
.Xr a-new-hope 7
- A New Hope (12/19/2019)
.El
.Sh SEE ALSO
.Bl -bullet -compact
.It
.Xr intro 7
.El
