.Dd March 24, 2020
.Dt DOMAIN-NAMES 7
.Os
.Sh NAME
.Nm domain-names
.Nd what's in a (domain) name?
.Sh DESCRIPTION
I went through a phase this week of really wanting `karle.[original-tld]`.
Not for a business.
Not for boosting my own webpage (it doesn't really have much).
Just for me.
.Pp
The results were... disheartening.
.Bl -bullet -compact -format=indent
.It
.Sy karle.org :
.Pp
Registered since 2004, no website, just an email DNS record.
WHOIS guard ensures I can't even reach out to who owns it.
.It
.Sy karle.com :
.Pp
For sale by owner on Uniregistry.
Ok.
Inquired.
Owner wants a "serious 5 figure offer".
Next!
.It
.Sy karle.net :
.Pp
Owned by
.Lk https://realnames.com RealNames ,
a business seemingly centered around buying lastname.net domains and
charging people like me to set up an email.
Almost brilliant enough of a business to make me forgive their scumminess.
.Em Almost .
Nary an option to buy it.
.El
So here we are. Looks like `karle.co` for at least a little longer.
.Sh SEE ALSO
.Bl -compact -bullet -format=indent
.It
.Xr blog 7
.El
