.Dd $Mdocdate$
.Dt INTRO 7
.Os
.Sh NAME
.Nm intro
.Nd welcome to my personal website
.Sh ABOUT ME
Hi!
I'm Alex.
I'm a software engineer living in the Boston area.
My current technical interests include free Operating Systems, version control,
and developer tooling, but I'm constantly learning new tech that I get excited
about.
Occasionally, I might write about it here on my
.Xr blog 7 .
.Pp
Outside of tech, I enjoy playing music, hiking, and a good board game
shared among friends.
.Pp
If you can't tell from the layout of this site, I'm a
.Xr man 1
page enthusiast.
.Sh SEE ALSO
.Bl -bullet -compact
.It
.Lk https://euchre.live euchre(6)
.It
.Xr blog 7
.It
.Lk /git projects(7)
.It
.Xr jam-tuesday 7
.El
.Sh CONTACT
Email: contact AT this-domain
