.Dd $Mdocdate$
.Dt INTRO 7
.Os
.Sh NAME
.Nm intro
.Nd welcome to my personal homepage
.Sh ABOUT ME
Hi!
I'm Alex.
I'm a software engineer living in the Boston area.
I'm currently interested in free Operating Systems (particularly Linux
and OpenBSD), SCM systems (mostly git), and developer tooling.
.Pp
If you can't tell from the layout of this site, I'm a
.Xr man 1
page enthusiast.
.Sh SEE ALSO
.Bl -bullet -compact
.It
.Lk https://euchre.live euchre(6)
.It
.Xr blog 7
.It
.Lk /git projects(7)
.El
.Sh CONTACT
Email:
.Mt alex@alexkarle.com
