.Dd $Mdocdate$
.Dt JAM-TUESDAY 7
.Os
.Sh NAME
.Nm jam-tuesday
.Nd setlists and notes from weekly jams
.Sh DESCRIPTION
For the better part of 2020 and carrying on today,
my brother Matt and I have gotten together every Tuesday evening to play music.
It started as a way to stay sane during the COVID quarantine,
but it quickly became a tradition and a highlight of the week.
No matter how stressful work was,
or what was going on in the outside world,
we could leave it all behind as we played some of our favorite tunes.
.Pp
At some point (woefully late),
I realized it would be fun to start cataloging what we played.
Now that I've got more than a handful recorded,
I thought it would be fun to share!
.Pp
The setlists and some 'greatest-hits' stats are all plaintext files served up here:
.Pp
.Lk https://alexkarle.com/jam-tuesday/
.Pp
There are no recordings (at least publically),
but there's a stray note here and there to "set the scene".
.Pp
Oh, and, unless otherwise noted,
I'm on guitar and Matt's on keys
(and if only one instrument is specified, it's me switching).
We both (attempt to) sing.
Sometimes we even harmonize :)
.Sh SEE ALSO
.Bl -bullet -compact
.It
.Xr intro 7
.It
.Xr blog 7
.El
