.Dd $Mdocdate$
.Dt LICENSE 7
.Os
.Sh NAME
.Nm license
.Nd copyright info for this site
.Sh COPYRIGHT
Except where otherwise noted,
all content on this site is licensed under a
Creative Commons Attribution 4.0 license (CC BY 4.0).
.Pp
Any code snippets, including the code used to build this site,
are licensed under a MIT license.
.Sh SEE ALSO
.Bl -bullet -compact
.It
.Lk https://creativecommons.org/licenses/by/4.0/ CC BY 4.0
.It
.Lk /LICENSE MIT license
.It
.Lk https://alexkarle.com/git/alexkarle.com Source code for the site
.It
.Xr intro 7
.It
.Xr blog 7
.El
