.Dd October 22, 2020
.Dt ON-WRITING 7
.Os
.Sh NAME
.Nm on-writing
.Nd thoughts on writing without an audience
.Sh DESCRIPTION
I wrote a blog post 3 weeks ago but never published it.
I spent a couple hours writing, proof-reading, and rewriting, and settled to
re-read once more in the morning and publish if I still liked it after a good
nights sleep.
.Pp
I got caught up with other things, and a day or two later re-read it and
still didn't end up publishing it.
I didn't think it was quite right.
I liked it well enough, but I was worried other people would judge it.
.Pp
But here's the irony
\(em
as far as I know, I have no readers.
Publishing it is almost equivalent to shouting into the void.
.Pp
So why did I care so much?
.Pp
As I found myself thinking about how I'd revise the original post
tonight, I realized that maybe this fear of judgment from non-existent
(but potential future) internet strangers was a much more interesting
topic to explore than my original musings.
So here I am hashing it out.
.Pp
I think the fear of judgment comes from a mixture of seeing public figures
have their pasts (preserved in the digital era) come back to haunt them
combined with observing how readers can react strongly and negatively to
posts.
I don't plan to ever become so famous as to have a blog haunt me,
nor do I ever expect enough readers to have overwhelmingly unpleasant
reactions, but the fear still got to me.
.Pp
But I want to persevere, and that's ultimately what writing this is about.
I'm not writing for fame or attention.
I'm not writing to further my career or put it on my resume.
I'm writing for me.
For the clarity I get from expressing my thoughts, and for
the joy I get looking back at where I was months or years ago.
.Pp
Why host them publicly?
Well, I really enjoy a good tech blog, and admire a blogger or two out there.
I want to be the change I want to see in the internet and migrate from
centralized social networks back to a decentralized network of personal and
self-hosted sites.
.Pp
And who knows, maybe one day someone will read this and have felt the same.
I guess I'm writing for that person too.
.Sh SEE ALSO
.Bl -bullet -compact
.It
.Xr blog 7
.El
