.Dd May 11, 2021
.Dt USES 7
.Os
.Sh NAME
.Nm uses
.Nd list of software/hardware I use
.Sh DESCRIPTION
I really enjoy a good "uses" post.
I think the first I ever stumbled across was Wes Bos',
back when I was learning web-development.
As someone fascinated by developer tooling,
I loved hearing what other programmers use in their day-to-day lives.
.Pp
I try to keep this page up to date,
both for my future nostalgia
as well as for anyone else out there who enjoys the "genre".
.Sh SOFTWARE
.Ss Editor
I got hooked on
.Lk https://www.vim.org vim(1)
mid-college (~2017) and never looked back.
It's first on this list (with a dedicated section!)
because it was the "gateway program"
that got me interested in developer tooling in the first place!
If not my most important tool,
it's definitely the most impactful.
.Pp
Other editors I use:
.Pp
.Bl -bullet -compact
.It
.Xr vi 1
for system configs (super snappy on OpenBSD)
.It
.Xr ed 1
for fun and for slow/serial connections (yes, really!)
.El
.Pp
I try emacs every once and a while because I think Lisp is awesome
(and far superior to VimScript),
but I don't really dig the "run everything in emacs" approach.
.Ss Operating System
I've been passionate about running free and open source (FOSS)
operating systems
since ~2019 when I first started using Linux seriously at work.
I'm currently running:
.Pp
.Bl -compact -bullet
.It
.Lk https://openbsd.org OpenBSD
for my server (hosting this site \(em see
.Xr self-hosted 7 ) ,
as well as my home router/firewall (as of early 2021)
.It
.Lk https://debian.org Debian
for my desktop (good support for work-related software)
.It
.Lk https://alpinelinux.org Alpine Linux
on my laptop (OpenBSD sometimes too, although it runs hot)
.El
.Pp
In the past I've also used
.Lk https://archlinux.org Arch Linux
(~2 years) and before that I was on macOS.
.Ss Other
Generally, you'll see a skew towards keyboard driven,
"simple" (less features),
and terminal applications.
Roughly in order of first-use:
.Pp
.Bl -compact -bullet
.It
.Lk https://git-scm.com/ git(1)
for notes, code, config backups (~2016, usage increased over time)
.It
.Xr tmux 1
for terminal scrollback, searching, copy/paste buffers, multiplexing,
persistent sessions over dropped
.Xr ssh 1
connections... really a necessity! (~2018)
.It
.Lk https://www.gnu.org/software/bash/ bash(1)
as my Linux shell (zsh previously, moved for work reasons early-2018)
.It
.Lk https://dwm.suckless.org/ dwm(1)
as my window manager (since early Linux days, early-2019)
.It
.Lk https://st.suckless.org/ st(1)
as my terminal emulator (also early-2019)
.It
.Lk http://mutt.org mutt(1)
for personal email (great for mailing lists, mid-2019)
.It
.Xr ksh 1
on OpenBSD for shells (late-2019)
.It
.Lk https://www.passwordstore.org pass(1)
for password/secret management (late-2020)
.El
.Pp
Not currently in use but notable:
.Pp
.Bl -compact -bullet
.It
.Lk https://xfce.org/ Xfce
really helped me transition to Linux.
I revisit occasionally to see what's going on,
but I always go back to the more minimal, keyboard-driven, dwm.
.El
.Sh HARDWARE
.Ss Keyboard
After years of mushy laptop keyboards,
I discovered mechanical keyboards through a coworker and
I've been clicking and clacking happily ever since!
.Pp
.Bl -bullet -compact
.It
.Lk https://uhk.io Ultimate Hacking Keyboard
was my first (Kailh browns, early-2019 to Dec-2020)
.It
.Lk https://shop.keyboard.io/pages/atreus Keyboardio Atreus
currently, successfully reducing finger movement / strain (Kailh BOX white, Dec-2020)
.El
.Ss Laptop
When I started really getting into Linux at work and home ~2019,
I installed Arch on my old macbook and suffered at the hands of
NVIDIA and poor hardware support until I ditched my macbook for
a ThinkPad X220 (2011, i7, 2GB RAM) that I bought used for ~$130 off Ebay.
A simple upgrade to a SSD and it runs great!
.Pp
I use the laptop for casual browsing and hobby coding
(I try to ensure my hobby projects all run on old hardware!),
but its CPU age really shows on big websites or compilations.
.Ss Desktop
I built my first desktop (a long standing nerd goal of mine) at the
start of the COVID-19 pandemic in 2020 when it became clear I'd be
working from home and my 2GB of laptop RAM wouldn't cut it.
.Pp
I tried (and failed) to keep the parts entirely FOSS-friendly,
but I ended up getting a GPU that needed the AMDGPU firmware blobs
(hard to find a fully free graphics card these days it seems).
With a high-end CPU (AMD Ryzen 7 3700X)
but a low-end GPU (Radeon RX 560),
it was a reasonable price.
And with 16GB of RAM, it handles my work environment well.
.Sh SEE ALSO
.Bl -bullet -compact
.It
.Xr blog 7
.It
.Lk https://wesbos.com/uses Wes Bos' uses page
.El
