.Dd $Mdocdate$
.Dt USES 7
.Os
.Sh NAME
.Nm uses
.Nd up-to-date list of software/hardware I use
.Sh DESCRIPTION
I really enjoy a good "uses" post.
I think the first I ever stumbled across was Wes Bos',
back when I was learning web-development.
As someone fascinated by developer tooling,
I loved hearing what other programmers use in their day-to-day lives.
.Pp
I try to keep this page up to date,
both for my future nostalgia,
as well as anyone else out there who enjoys the "genre".
.Sh SOFTWARE
.Ss Editor
I use a lightly customized
.Lk https://www.vim.org vim(1)
for development and
.Xr vi 1
in a pinch.
.Pp
Of the plugins I use, the ones I feel really give me a lift are:
.Bl -bullet -compact
.It
.Lk https://github.com/tpope/vim-fugitive vim-fugitive
for interactive staging, diffs (cross branches even), and :Ggrep.
.It
.Lk https://github.com/tpope/vim-surround vim-surround
really just helps refactoring code (especially strings)
.It
.Lk https://github.com/justinmk/vim-dirvish vim-dirvish
as a faster,
safer file-browser.
I know Vim ships with netrw,
but I like knowing that a stray key won't delete my files.
.El
Oh and being a general fan of retro-computing, I've really enjoyed learning
.Xr ed 1
(blog post pending).
.Ss OS
I use OpenBSD to host this site (big fan \(em see 
.Xr self-hosted 7 ) ,
but due to a couple unfortunate graphics bugs,
haven't been successful in using it on the Desktop.
.Pp
I use Debian on my PC (plays nicely with necessary software for work) 
and Alpine on an old ThinkPad X220.
.Pp
I've been using solely free OS' for a couple years now and really
appreciate the transparency and ability to dive-deeply into the source.
.Ss Desktop Environment / Window Manager
I've been using
.Lk https://dwm.suckless.org/ dwm(1)
for about as long as I've been on Linux and keep coming back to it.
.Pp
I really dig how snappy it is on my old laptop and that it is heavily keyboard driven.
While configurability is certainly a feature,
I've found that after an initial period of making changes in the first few months,
my config has stayed mostly unchanged.
.Pp
.Ss Miscellaneous
Core to my setup is
.Xr tmux 1 ,
which I use to manage any number of terminal programs I might
have running (open
.Xr ssh 1
connections,
Vim instances,
and a multitude of shells to do any number of tasks).
.Pp
Since moving to primarily WFH during the COVID pandemic, I've especially
come to appreciate the client-server architecture of
.Xr tmux 1 ,
which saves me almost daily when spotty VPN connections drop.
.Pp
Other honorable mentions are
.Lk http://mutt.org mutt(1)
for email and 
.Lk https://git-scm.com/ git(1)
for backing up code, notes, and config files.
.Pp
.Sh HARDWARE
.Ss Keyboard
I used the
.Lk https://uhk.io Ultimate Hacking Keyboard
for about two years before deciding
I wanted to try something a bit more ergonomic.
I've been using the
.Lk https://shop.keyboard.io/pages/atreus Keyboardio Atreus 
since December 2020 and really enjoying it. 
.Ss Laptop
When I started really getting into Linux at work and home ~2019,
I installed Arch on my old macbook and suffered at the hands of
NVIDIA and poor hardware support until I ditched my macbook for
a X220 that I bought off Ebay and put a SSD in.
I've been using that same X220 (i7, 2GB RAM) ever since,
although when I started working from home during the COVID-19 pandemic
I had to upgrade to something that could run my work environment,
so I invested in a desktop.
.Pp
I run either Alpine Linux or OpenBSD on my laptop (swapping hard drives
like nintendo cartidges :) ).
I prefer the latter, but the former runs much cooler.
.Ss Desktop
I built my first desktop (a long standing nerd goal of mine) at the
start of the COVID-19 pandemic in 2020.
I use it for all work-related development,
and use my laptop for casual browsing and hobby coding
(I try to ensure my hobby projects all run on old hardware!).
.Pp
My desktop runs Debian,
since I find most work-related software runs on it.
.Sh SEE ALSO
.Bl -bullet -compact
.It
.Xr blog 7
.It
.Lk https://wesbos.com/uses Wes Bos' uses page
.El
