#!/bin/sh
# based off of: https://rgz.ee/stagit.html
set -e
dst="/var/www/htdocs/git/$(basename "$(pwd)" '.git')"
src="$(pwd)"

# KEY: run in background (saves a slow push)
mkdir -p "$dst"
(cd "$dst" && stagit "$src")
cp -f "$dst/log.html" "$dst/index.html"

# Assume run as git, so $HOME has the repos
exported="$(ls $HOME/*.git/git-daemon-export-ok | sed 's/\/git-daemon-export-ok//g')"
stagit-index $exported > /var/www/htdocs/git/index.html
